<?php

namespace App\Support;

/**
 * # Generated by AI
 * Test card numbers for payment simulation
 * Industry standard approach (like Stripe, PayPal sandbox)
 */
class TestCards
{
    // Success cards
    public const SUCCESS_VISA = '4242424242424242';
    public const SUCCESS_MASTERCARD = '5555555555554444';
    public const SUCCESS_AMEX = '378282246310005';

    // Decline cards
    public const DECLINE_GENERIC = '4000000000000002';
    public const DECLINE_INSUFFICIENT_FUNDS = '4000000000009995';
    public const DECLINE_LOST_CARD = '4000000000009987';

    // Error cards
    public const ERROR_PROCESSING = '4000000000000119';
    public const ERROR_EXPIRED = '4000000000000069';

    private const SUCCESS_CARDS = [
        self::SUCCESS_VISA,
        self::SUCCESS_MASTERCARD,
        self::SUCCESS_AMEX,
    ];

    private const DECLINE_CARDS = [
        self::DECLINE_GENERIC => 'Card declined',
        self::DECLINE_INSUFFICIENT_FUNDS => 'Insufficient funds',
        self::DECLINE_LOST_CARD => 'Card reported lost',
    ];

    private const ERROR_CARDS = [
        self::ERROR_PROCESSING => 'Processing error',
        self::ERROR_EXPIRED => 'Card expired',
    ];

    public static function isSuccess(string $cardNumber): bool
    {
        return in_array(self::normalize($cardNumber), self::SUCCESS_CARDS);
    }

    public static function isDeclined(string $cardNumber): bool
    {
        return array_key_exists(self::normalize($cardNumber), self::DECLINE_CARDS);
    }

    public static function getDeclineReason(string $cardNumber): string
    {
        return self::DECLINE_CARDS[self::normalize($cardNumber)] ?? 'Card declined';
    }

    public static function isError(string $cardNumber): bool
    {
        return array_key_exists(self::normalize($cardNumber), self::ERROR_CARDS);
    }

    public static function getErrorReason(string $cardNumber): string
    {
        return self::ERROR_CARDS[self::normalize($cardNumber)] ?? 'Processing error';
    }

    private static function normalize(string $cardNumber): string
    {
        return preg_replace('/\D/', '', $cardNumber);
    }
}
